basePath: /api/v1
definitions:
  ErrorStruct:
    properties:
      ErrorCode:
        type: integer
      ErrorMessage:
        type: string
    type: object
  v1.benefitResponse:
    properties:
      city_id:
        type: string
      description:
        type: string
      how_to_use:
        type: string
      id:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      region_id:
        type: string
      requirement:
        type: string
      source_url:
        type: string
      target_groups:
        items:
          type: string
        type: array
      title:
        type: string
      type:
        type: string
      valid_from:
        type: string
      valid_to:
        type: string
    type: object
  v1.benefitsListResponse:
    properties:
      benefits:
        items:
          $ref: '#/definitions/v1.benefitResponse'
        type: array
    type: object
  v1.exchangeTokenRequest:
    properties:
      code:
        type: string
      state:
        type: string
    required:
    - code
    - state
    type: object
  v1.exchangeTokenResponse:
    properties:
      access_token:
        type: string
    type: object
info:
  contact: {}
  description: Backend API
  title: Backend API
  version: "1.0"
paths:
  /benefits:
    get:
      consumes:
      - application/json
      description: Получить список всех льгот
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.benefitsListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorStruct'
      summary: Get Benefits List
      tags:
      - Benefits
  /benefits/{id}:
    get:
      consumes:
      - application/json
      description: Получить льготу по ID
      parameters:
      - description: Benefit ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.benefitResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorStruct'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/ErrorStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorStruct'
      summary: Get Benefit By ID
      tags:
      - Benefits
  /users/auth/callback:
    get:
      consumes:
      - application/json
      description: Callback endpoint для Auth - получает code от ESIA и редиректит
        на фронтенд
      parameters:
      - description: Authorization code
        in: query
        name: code
        required: true
        type: string
      - description: State parameter
        in: query
        name: state
        required: true
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Redirect to frontend with code
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorStruct'
      summary: OAuth Callback
      tags:
      - Auth
  /users/auth/login:
    get:
      consumes:
      - application/json
      description: Перенаправление на ESIA для авторизации
      produces:
      - application/json
      responses:
        "302":
          description: Found
      summary: OAuth Login
      tags:
      - Auth
  /users/auth/token:
    post:
      consumes:
      - application/json
      description: Обмен authorization code на access и refresh токены (как в Keycloak)
      parameters:
      - description: Code и State
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.exchangeTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.exchangeTokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorStruct'
      summary: Exchange Code for Tokens
      tags:
      - Auth
  /users/pong:
    get:
      consumes:
      - application/json
      description: Pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorStruct'
        "500":
          description: Internal Server Error
      security:
      - UserAuth: []
      summary: Pong
      tags:
      - Pong
securityDefinitions:
  AdminAuth:
    in: header
    name: Authorization
    type: apiKey
  UserAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
